const mongoose = require('mongoose');

const AgreementRequestsSchema = new mongoose.Schema({
  property_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Properties' },
  customer_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  owner_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  broker_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  property_admin_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  request_message: { type: String },
  customer_notes: { type: String },
  admin_notes: { type: String },
  owner_notes: { type: String },
  response_message: { type: String },
  status: { type: String },
  current_step: { type: Number },
  property_price: { type: Number },
  proposed_price: { type: Number },
  commission_percentage: { type: Number },
  total_commission: { type: Number },
  owner_decision: { type: String },
  owner_decision_date: { type: Date },
  admin_action: { type: String },
  admin_action_date: { type: Date },
  move_in_date: { type: Date },
  buyer_signed: { type: Boolean },
  owner_signed: { type: Boolean },
  broker_signed: { type: Boolean },
  buyer_signed_date: { type: Date },
  owner_signed_date: { type: Date },
  broker_signed_date: { type: Date },
  payment_submitted: { type: Boolean },
  payment_confirmed: { type: Boolean },
  payment_verified: { type: Boolean },
  payment_verified_date: { type: Date },
  payment_verified_by: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  payment_receipt_id: { type: mongoose.Schema.Types.ObjectId },
  handover_confirmed: { type: Boolean },
  handover_confirmed_date: { type: Date },
  funds_released: { type: Boolean },
  funds_released_date: { type: Date },
  funds_released_by: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  request_date: { type: Date },
  forwarded_to_owner_date: { type: Date },
  agreement_generated_date: { type: Date },
  customer_submitted_date: { type: Date },
  owner_final_submitted_date: { type: Date },
  completion_date: { type: Date },
  owner_response_date: { type: Date },
  responded_by: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  responded_at: { type: Date },
  broker_engagement_id: { type: mongoose.Schema.Types.ObjectId, ref: 'BrokerEngagements' },
  created_at: { type: Date },
  updated_at: { type: Date },
  rental_duration_months: { type: Number },
  payment_schedule: { type: String },
  agreement_type: { type: String },
  security_deposit: { type: Number },
  completed_date: { type: Date },
  is_direct_agreement: { type: Boolean },
  system_fee_payer: { type: String },
  counter_offer_price: { type: Number },
  negotiation_rounds: { type: Number },
  media_released: { type: Boolean },
  media_released_at: { type: Date },
  media_released_by: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  media_viewed: { type: Boolean },
  media_viewed_at: { type: Date },
  video_verified: { type: Boolean },
  video_verified_at: { type: Date },
  video_verified_by: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  video_url: { type: String },
  video_uploaded_at: { type: Date },
  buyer_handover_confirmed: { type: Boolean },
  buyer_handover_date: { type: Date },
  owner_handover_confirmed: { type: Boolean },
  owner_handover_date: { type: Date },
  payment_method: { type: String },
  payment_reference: { type: String },
  payment_amount: { type: Number },
  receipt_document: { type: String },
}, { timestamps: true });

module.exports = mongoose.model('AgreementRequests', AgreementRequestsSchema);
