const mongoose = require('mongoose');

const BrokerEngagementsSchema = new mongoose.Schema({
  buyer_id: { type: mongoose.Schema.Types.ObjectId },
  broker_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  property_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Properties' },
  owner_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  status: { type: String },
  starting_offer: { type: Number },
  current_offer: { type: Number },
  agreed_price: { type: Number },
  buyer_message: { type: String },
  broker_advice: { type: String },
  broker_recommendation: { type: String },
  owner_counter_price: { type: Number },
  owner_counter_message: { type: String },
  buyer_authorization: { type: String },
  buyer_auth_counter_price: { type: Number },
  buyer_auth_message: { type: String },
  broker_decline_reason: { type: String },
  commission_percentage: { type: Number },
  agreement_request_id: { type: mongoose.Schema.Types.ObjectId, ref: 'AgreementRequests' },
  created_at: { type: Date },
  updated_at: { type: Date },
  broker_accepted_at: { type: Date },
  owner_responded_at: { type: Date },
  broker_advised_at: { type: Date },
  buyer_authorized_at: { type: Date },
  finalized_at: { type: Date },
  contract_generated_at: { type: Date },
  completed_at: { type: Date },
  engagement_type: { type: String },
  rental_duration_months: { type: Number },
  payment_schedule: { type: String },
  security_deposit: { type: Number },
  draft_offer_price: { type: Number },
  buyer_handover_confirmed: { type: Boolean },
  owner_handover_confirmed: { type: Boolean },
  payment_method: { type: String },
  payment_reference: { type: String },
  payment_receipt: { type: String },
  contract_html: { type: String },
  payment_submitted_at: { type: Date },
  payment_verified_at: { type: Date },
  payment_verified_by: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  handover_confirmed_at: { type: Date },
  system_commission_pct: { type: Number },
  broker_commission_pct: { type: Number },
  system_commission_amount: { type: Number },
  broker_commission_amount: { type: Number },
  owner_payout_amount: { type: Number },
  funds_released_at: { type: Date },
  funds_released_by: { type: mongoose.Schema.Types.ObjectId, ref: 'Users' },
  buyer_commission_offer: { type: Number },
  broker_commission_counter: { type: Number },
  agreed_commission_pct: { type: Number },
  commission_negotiation_status: { type: String },
  system_fee_payer: { type: String },
}, { timestamps: true });

module.exports = mongoose.model('BrokerEngagements', BrokerEngagementsSchema);
